export const categorySeeds = [
  {
    name: "ホーム・生活雑貨",
    slug: "home-living",
    description: "毎日の暮らしに馴染む、シンプルで長く使えるアイテムを揃えました。",
  },
  {
    name: "デジタル・家電",
    slug: "electronics",
    description: "使いやすさと心地よい操作感、長く使える品質を大切にしたアイテムです。",
  },
  {
    name: "アウトドア",
    slug: "outdoors",
    description: "軽量で扱いやすく、街歩きや日帰りのアウトドアに適したアイテムです。",
  },
  {
    name: "文具・オフィス",
    slug: "stationery",
    description: "筆記やデスクワークに集中しやすい環境を整えます。",
  },
  {
    name: "スポーツ・フィットネス",
    slug: "sports-fitness",
    description: "自宅でのトレーニングやストレッチ、日々の体力づくりに適しています。",
  },
] as const;

export const productSeeds = [
  {
    name: "ストーンテーブルランプ",
    slug: "stone-table-lamp",
    description:
      "天然石のような質感と柔らかな拡散光で、読書スペースを穏やかに照らすテーブルランプです。",
    price: 21500,
    categorySlug: "home-living",
    stock: 8,
    rating: 4.8,
    reviewCount: 24,
    salesCount: 158,
  },
  {
    name: "リネンクッション",
    slug: "linen-cushion",
    description:
      "高密度のリネン生地と弾力のある中材を組み合わせ、ソファやチェア、寝室で使いやすいクッションです。",
    price: 6800,
    categorySlug: "home-living",
    stock: 3,
    rating: 4.6,
    reviewCount: 17,
    salesCount: 96,
  },
  {
    name: "スタジオヘッドホン",
    slug: "studio-headphones",
    description:
      "密閉型の音響設計と軽量ヘッドバンドにより、クリアなモニタリングと長時間でも快適な装着感を実現します。",
    price: 32900,
    categorySlug: "electronics",
    stock: 12,
    rating: 4.9,
    reviewCount: 42,
    salesCount: 211,
  },
  {
    name: "メカニカルキーボード",
    slug: "mechanical-keyboard",
    description:
      "コンパクトな配列、ホットスワップ対応スイッチ、落ち着いた配色で、快適なタイピングを支えます。",
    price: 18900,
    categorySlug: "electronics",
    stock: 0,
    rating: 4.7,
    reviewCount: 31,
    salesCount: 184,
  },
  {
    name: "軽量ボトル",
    slug: "trail-bottle",
    description:
      "丈夫なステンレスボトルと漏れにくいスクリューキャップを採用し、通勤やハイキング、日常の水分補給に適しています。",
    price: 4200,
    categorySlug: "outdoors",
    stock: 24,
    rating: 4.5,
    reviewCount: 19,
    salesCount: 302,
  },
  {
    name: "折りたたみデイパック",
    slug: "packable-daypack",
    description:
      "折りたためる軽量素材と複数の収納スペースを備え、旅行の予備バッグや街歩きに便利です。",
    price: 12800,
    categorySlug: "outdoors",
    stock: 6,
    rating: 4.6,
    reviewCount: 27,
    salesCount: 143,
  },
  {
    name: "真鍮ボールペン",
    slug: "brass-pen",
    description:
      "無垢の真鍮軸は使うほどに風合いが増し、ほどよい重さで安定した書き心地を楽しめます。",
    price: 5600,
    categorySlug: "stationery",
    stock: 15,
    rating: 4.8,
    reviewCount: 36,
    salesCount: 267,
  },
  {
    name: "方眼ノート",
    slug: "grid-notebook",
    description:
      "目にやさしい紙と淡い方眼罫を採用し、メモ、スケッチ、日々の計画に使いやすいノートです。",
    price: 1800,
    categorySlug: "stationery",
    stock: 42,
    rating: 4.4,
    reviewCount: 14,
    salesCount: 389,
  },
  {
    name: "真空ステンレスタンブラー",
    slug: "vacuum-stainless-tumbler",
    description:
      "二重真空構造のステンレス製で、漏れにくいスクリューキャップを採用。通勤や外出時の水分補給に便利です。",
    price: 3480,
    categorySlug: "outdoors",
    stock: 36,
    images: ["/products/vacuum-stainless-tumbler.svg"],
    rating: 4.7,
    reviewCount: 18,
    salesCount: 74,
  },
  {
    name: "調光デスクライト",
    slug: "soft-reading-desk-lamp",
    description:
      "角度を調整できるアームと柔らかな拡散シェードで、読書や筆記、夜間のデスクワークを均一に照らします。",
    price: 5980,
    categorySlug: "home-living",
    stock: 18,
    images: ["/products/soft-reading-desk-lamp.svg"],
    rating: 4.6,
    reviewCount: 22,
    salesCount: 61,
  },
  {
    name: "ラバーコーティング六角ダンベル",
    slug: "hex-coated-dumbbell",
    description:
      "転がりにくい六角形と床を傷つけにくいラバーコーティングで、自宅での筋力トレーニングに適しています。",
    price: 4500,
    categorySlug: "sports-fitness",
    stock: 20,
    images: ["/products/hex-coated-dumbbell.svg"],
    rating: 4.8,
    reviewCount: 31,
    salesCount: 92,
  },
  {
    name: "クッションヨガマット",
    slug: "cushioned-yoga-mat",
    description:
      "細かな滑り止め加工と適度なクッション性で、ヨガ、ストレッチ、体幹トレーニングを快適に行えます。",
    price: 3980,
    categorySlug: "sports-fitness",
    stock: 28,
    images: ["/products/cushioned-yoga-mat.svg"],
    rating: 4.7,
    reviewCount: 26,
    salesCount: 87,
  },
  {
    name: "二段保温ランチボックス",
    slug: "double-insulated-lunch-box",
    description:
      "二段の独立容器と密閉ふたで主食とおかずを分けて収納でき、オフィスランチや日常の持ち運びに便利です。",
    price: 4200,
    categorySlug: "home-living",
    stock: 24,
    images: ["/products/double-insulated-lunch-box.svg"],
    rating: 4.5,
    reviewCount: 17,
    salesCount: 53,
  },
  {
    name: "アルミ製ノートPCスタンド",
    slug: "aluminum-laptop-stand",
    description:
      "開放的なアルミ構造で画面の高さと放熱性を確保し、折りたたんで持ち運べるノートPCスタンドです。",
    price: 5200,
    categorySlug: "stationery",
    stock: 22,
    images: ["/products/aluminum-laptop-stand.svg"],
    rating: 4.8,
    reviewCount: 29,
    salesCount: 104,
  },
  {
    name: "モジュール式デスクオーガナイザー",
    slug: "modular-desk-organizer",
    description:
      "高さの異なる収納部に筆記具や付箋、小物を整理でき、角の丸いモジュールを自由に組み合わせられます。",
    price: 2900,
    categorySlug: "stationery",
    stock: 40,
    images: ["/products/modular-desk-organizer.svg"],
    rating: 4.4,
    reviewCount: 15,
    salesCount: 68,
  },
  {
    name: "静音ワイヤレスマウス",
    slug: "silent-wireless-mouse",
    description:
      "軽量で左右対称の形状と静音ボタンを採用し、オフィスや共有スペース、外出先での作業に適しています。",
    price: 3600,
    categorySlug: "electronics",
    stock: 32,
    images: ["/products/silent-wireless-mouse.svg"],
    rating: 4.6,
    reviewCount: 34,
    salesCount: 126,
  },
  {
    name: "折りたたみ携帯扇風機",
    slug: "folding-portable-fan",
    description:
      "折りたたみスタンドで手持ちと卓上の両方に対応。風量を切り替えられ、通勤時やデスク周りで便利です。",
    price: 2980,
    categorySlug: "electronics",
    stock: 45,
    images: ["/products/folding-portable-fan.svg"],
    rating: 4.5,
    reviewCount: 21,
    salesCount: 83,
  },
  {
    name: "5段階トレーニングバンドセット",
    slug: "five-level-resistance-bands",
    description:
      "5段階の負荷レベルで強度を調整でき、ウォームアップ、ストレッチ、自宅での全身トレーニングに適しています。",
    price: 2600,
    categorySlug: "sports-fitness",
    stock: 50,
    images: ["/products/five-level-resistance-bands.svg"],
    rating: 4.7,
    reviewCount: 38,
    salesCount: 139,
  },
] as const;
