export const categorySeeds = [
  { name: "家居生活", slug: "home-living", description: "为日常空间选择克制而耐用的物件。" },
  { name: "数码设备", slug: "electronics", description: "兼顾效率、触感与长期使用体验。" },
  { name: "户外出行", slug: "outdoors", description: "轻量、可靠，适合城市与短途户外。" },
  { name: "文具办公", slug: "stationery", description: "让书写与桌面工作更专注。" },
  { name: "运动健身", slug: "sports-fitness", description: "适合居家训练、拉伸和日常体能练习。" },
] as const;

export const productSeeds = [
  {
    name: "岩石台灯",
    slug: "stone-table-lamp",
    description: "天然石材质感与柔和漫射光结合，为阅读角落提供安静而温暖的照明。",
    price: 21500,
    categorySlug: "home-living",
    stock: 8,
    rating: 4.8,
    reviewCount: 24,
    salesCount: 158,
  },
  {
    name: "亚麻靠垫",
    slug: "linen-cushion",
    description: "高密度亚麻外层搭配弹性填充，适合沙发、座椅和卧室的日常使用。",
    price: 6800,
    categorySlug: "home-living",
    stock: 3,
    rating: 4.6,
    reviewCount: 17,
    salesCount: 96,
  },
  {
    name: "录音室耳机",
    slug: "studio-headphones",
    description: "封闭式声学结构与轻量头梁设计，提供清晰监听和长时间佩戴舒适度。",
    price: 32900,
    categorySlug: "electronics",
    stock: 12,
    rating: 4.9,
    reviewCount: 42,
    salesCount: 211,
  },
  {
    name: "机械键盘",
    slug: "mechanical-keyboard",
    description: "紧凑布局、热插拔轴体和低饱和配色，为桌面工作提供稳定输入体验。",
    price: 18900,
    categorySlug: "electronics",
    stock: 0,
    rating: 4.7,
    reviewCount: 31,
    salesCount: 184,
  },
  {
    name: "轻量随行水瓶",
    slug: "trail-bottle",
    description: "耐用不锈钢瓶身配合防漏旋盖，适合通勤、徒步和日常补水。",
    price: 4200,
    categorySlug: "outdoors",
    stock: 24,
    rating: 4.5,
    reviewCount: 19,
    salesCount: 302,
  },
  {
    name: "折叠日用背包",
    slug: "packable-daypack",
    description: "可折叠轻量面料与多层收纳结构，兼顾旅行备用和城市短途使用。",
    price: 12800,
    categorySlug: "outdoors",
    stock: 6,
    rating: 4.6,
    reviewCount: 27,
    salesCount: 143,
  },
  {
    name: "黄铜中性笔",
    slug: "brass-pen",
    description: "实心黄铜笔身会随使用形成独特光泽，平衡重量带来稳定书写手感。",
    price: 5600,
    categorySlug: "stationery",
    stock: 15,
    rating: 4.8,
    reviewCount: 36,
    salesCount: 267,
  },
  {
    name: "方格笔记本",
    slug: "grid-notebook",
    description: "柔和护眼纸张搭配浅色方格，适合记录、草图和日常项目规划。",
    price: 1800,
    categorySlug: "stationery",
    stock: 42,
    rating: 4.4,
    reviewCount: 14,
    salesCount: 389,
  },
  {
    name: "真空不锈钢随行杯",
    slug: "vacuum-stainless-tumbler",
    description: "双层真空不锈钢杯体搭配防漏旋盖，适合通勤饮水与短途出行。",
    price: 3480,
    categorySlug: "outdoors",
    stock: 36,
    images: ["/products/vacuum-stainless-tumbler.svg"],
    rating: 4.7,
    reviewCount: 18,
    salesCount: 74,
  },
  {
    name: "柔光阅读台灯",
    slug: "soft-reading-desk-lamp",
    description: "可调角度灯臂与柔和扩散灯罩，为阅读、书写和夜间桌面工作提供均匀照明。",
    price: 5980,
    categorySlug: "home-living",
    stock: 18,
    images: ["/products/soft-reading-desk-lamp.svg"],
    rating: 4.6,
    reviewCount: 22,
    salesCount: 61,
  },
  {
    name: "六角包胶哑铃",
    slug: "hex-coated-dumbbell",
    description: "防滚六角造型配合缓冲包胶表面，适合居家力量训练与基础动作练习。",
    price: 4500,
    categorySlug: "sports-fitness",
    stock: 20,
    images: ["/products/hex-coated-dumbbell.svg"],
    rating: 4.8,
    reviewCount: 31,
    salesCount: 92,
  },
  {
    name: "缓冲瑜伽垫",
    slug: "cushioned-yoga-mat",
    description: "细密防滑纹理与适中缓冲厚度兼顾稳定和舒适，适合瑜伽、拉伸与核心训练。",
    price: 3980,
    categorySlug: "sports-fitness",
    stock: 28,
    images: ["/products/cushioned-yoga-mat.svg"],
    rating: 4.7,
    reviewCount: 26,
    salesCount: 87,
  },
  {
    name: "双层保温饭盒",
    slug: "double-insulated-lunch-box",
    description: "双层独立内胆与密封上盖便于分装主食和配菜，适合办公室午餐与日常携带。",
    price: 4200,
    categorySlug: "home-living",
    stock: 24,
    images: ["/products/double-insulated-lunch-box.svg"],
    rating: 4.5,
    reviewCount: 17,
    salesCount: 53,
  },
  {
    name: "铝合金电脑支架",
    slug: "aluminum-laptop-stand",
    description: "开放式金属结构抬高屏幕并保留散热空间，折叠后便于收纳和携带。",
    price: 5200,
    categorySlug: "stationery",
    stock: 22,
    images: ["/products/aluminum-laptop-stand.svg"],
    rating: 4.8,
    reviewCount: 29,
    salesCount: 104,
  },
  {
    name: "模块化桌面收纳盒",
    slug: "modular-desk-organizer",
    description: "高低分区可整理笔具、便签和小型配件，圆角模块可自由组合桌面布局。",
    price: 2900,
    categorySlug: "stationery",
    stock: 40,
    images: ["/products/modular-desk-organizer.svg"],
    rating: 4.4,
    reviewCount: 15,
    salesCount: 68,
  },
  {
    name: "静音无线鼠标",
    slug: "silent-wireless-mouse",
    description: "轻量对称轮廓配合低噪按键，适合办公室、共享空间和移动办公使用。",
    price: 3600,
    categorySlug: "electronics",
    stock: 32,
    images: ["/products/silent-wireless-mouse.svg"],
    rating: 4.6,
    reviewCount: 34,
    salesCount: 126,
  },
  {
    name: "折叠便携风扇",
    slug: "folding-portable-fan",
    description: "可折叠支架支持手持与桌面两种方式，多档风量适合通勤和小空间降温。",
    price: 2980,
    categorySlug: "electronics",
    stock: 45,
    images: ["/products/folding-portable-fan.svg"],
    rating: 4.5,
    reviewCount: 21,
    salesCount: 83,
  },
  {
    name: "五级阻力带套装",
    slug: "five-level-resistance-bands",
    description: "五种阻力等级便于循序增加训练强度，适合热身、拉伸和居家全身训练。",
    price: 2600,
    categorySlug: "sports-fitness",
    stock: 50,
    images: ["/products/five-level-resistance-bands.svg"],
    rating: 4.7,
    reviewCount: 38,
    salesCount: 139,
  },
] as const;
